### PR TITLE
Fix hot-reload and revisit webpack configuration

### LINKED ISSUE #350: React hot reload is not working
**Describe the bug**
React hot reload is not working on boilerplate

**To Reproduce**
1. Follow all the steps on the boilerplate
2. Run the project
3. Open localhost:8000
4. Change code and see that the page is refreshing

Also there are a lot of 404 errors, this probably have something with the django webpack loader

**Expected behavior**
It should work

**Screenshots**
image

### PR DESCRIPTION
**Pull request by jhgv**
## Motivation and Context
Closes #350 #337 #173 #160 #395 #387 

## Steps to reproduce:
- [ ] Get the bootstrap and follow the setup
- [ ] Run the back and frontend
- [ ] Check if there are no errors in the console
- [ ] Check if hot reload is working 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires documentation updates.
- [ ] I have updated the documentation accordingly.
- [ ] My change requires dependencies updates.
- [ ] I have updated the dependencies accordingly.

### CODE REVIEW

File: frontend/js/index.js [hunk 1]
```diff
@@ -1,16 +1,17 @@
 // import pages
-import 'bootstrap-includes';
-import '../sass/style.scss';
-
 import React from 'react';
-import ReactDOM from 'react-dom';
 import * as Sentry from '@sentry/browser';
 
+import { render } from 'react-dom';
```
Comment (joaopslins) [inline frontend/js/index.js]: Use `ReactDOM`

File: webpack.base.config.js [hunk 2]
```diff
@@ -1,76 +1,54 @@
...
+  context: __dirname,
+  entry: [],
+  output: {
+    path: path.resolve(__dirname, 'frontend/bundles/'),
+  },
+  module: {
+    rules: [
+      {
+        test: /\.css$/,
+        use: [
```
Comment (joaopslins) [inline webpack.base.config.js]: Revert this config

File: webpack.base.config.js [hunk 3]
```diff
@@ -1,76 +1,54 @@
...
-          use: {
-            loader: 'babel-loader',
-            options: {
-              presets: ['@babel/preset-env'],
-            },
+const nodeModulesDir = path.resolve(__dirname, 'node_modules');
+
+const devMode = process.env.NODE_ENV !== 'production';
+
+module.exports = {
```
Comment (joaopslins) [inline webpack.base.config.js]: This should be the same as the previous one, I think there should be no changes for the purpose of this pr
